package org.irmc.industrialrevival.api.elements;

import lombok.Getter;
import org.irmc.industrialrevival.utils.ElementUtil;

/**
 * Represents an element type.
 * <p>
 * An element type is defined by its symbol, proton number, neutron number, valence, group, period,
 * density, melting point, boiling point, and other properties.
 * <p>
 * Be honest, all the data was generated by AI, so there may be some inaccuracies.
 *
 * @author balugaq
 * @author lijinhong11
 * @since 1.0
 */
@SuppressWarnings("unused")
@Getter
public enum ElementType {
    H("H", 1.008, 0, Valence.of(1, -1), false, ElementGroup.IA, 1, -259.2, -252.9, 0.08),
    He("He", 4.003, 0, Valence.of(0), false, ElementGroup.VIIIA, 1, -272.2, -268.9, 0.14),
    Li("Li", 6.941, 3, Valence.of(1), true, ElementGroup.IA, 2, 180.54, 1342, 0.534),
    Be("Be", 9.012, 4, Valence.of(2), true, ElementGroup.IIA, 2, 1278, 2970, 1.85),
    B("B", 10.81, 5, Valence.of(3), false, ElementGroup.IIIA, 2, 2076, 4000, 2.34),
    C("C", 12.01, 4, Valence.of(4, 2, -4), false, ElementGroup.IVA, 2, 3550, 4300, 2.26),
    N("N", 14.01, 5, Valence.of(3, 5, 1, -3, 2), false, ElementGroup.VA, 2, -210.01, -195.8, 1.25),
    O("O", 16.00, 6, Valence.of(2, -2), false, ElementGroup.VIA, 2, -218.4, -182.96, 1.43),
    F("F", 19.00, 7, Valence.of(1, -1), false, ElementGroup.VIIA, 2, -219.62, -188.14, 1.71),
    Ne("Ne", 20.18, 8, Valence.of(0), false, ElementGroup.VIIIA, 2, -248.59, -246.08, 0.8999),
    Na("Na", 22.99, 10, Valence.of(1), true, ElementGroup.IA, 3, 97.72, 1156, 0.97),
    Mg("Mg", 24.31, 12, Valence.of(2), true, ElementGroup.IIA, 3, 650, 1090, 1.74),
    Al("Al", 26.98, 13, Valence.of(3), true, ElementGroup.IIIA, 3, 660.3, 2467, 2.7),
    Si("Si", 28.09, 14, Valence.of(4, -4), false, ElementGroup.IVA, 3, 1414, 3265, 2.33),
    P("P", 30.97, 15, Valence.of(3, 5, -3), false, ElementGroup.VA, 3, 44.15, 280, 1.82),
    S("S", 32.06, 16, Valence.of(6, 4, 2), false, ElementGroup.VIA, 3, 115.21, 444.6, 2.07),
    Cl("Cl", 35.45, 17, Valence.of(7, 1, 3, 5), false, ElementGroup.VIIA, 3, -101.5, -34.04, 3.21),
    Ar("Ar", 39.95, 18, Valence.of(0), false, ElementGroup.VIIIA, 3, -189.2, -185.7, 1.63),
    K("K", 39.10, 19, Valence.of(1), true, ElementGroup.IA, 4, 63.65, 759, 0.86),
    Ca("Ca", 40.08, 20, Valence.of(2), true, ElementGroup.IIA, 4, 842, 1484, 1.55),
    Sc("Sc", 44.96, 21, Valence.of(3), true, ElementGroup.IIIB, 3, 1539, 2832, 2.99),
    Ti("Ti", 47.87, 22, Valence.of(4, 3), true, ElementGroup.IVB, 4, 1668, 3287, 4.51),
    V("V", 50.94, 23, Valence.of(5, 3), true, ElementGroup.VB, 4, 1910, 3407, 6.11),
    Cr("Cr", 52.00, 24, Valence.of(6, 3, 4), true, ElementGroup.VIB, 4, 1857, 2671, 7.19),
    Mn("Mn", 54.94, 25, Valence.of(7, 2, 3, 4, 5, 6), true, ElementGroup.VIIB, 4, 1244, 2095, 7.44),
    Fe("Fe", 55.85, 26, Valence.of(2, 3), true, ElementGroup.VIIIB, 4, 1538, 2862, 7.87),
    Co("Co", 58.93, 27, Valence.of(2, 3), true, ElementGroup.VIIIB, 4, 1495, 2870, 8.9),
    Ni("Ni", 58.69, 28, Valence.of(2, 3), true, ElementGroup.VIIIB, 4, 1453, 2732, 8.91),
    Cu("Cu", 63.55, 29, Valence.of(1, 2), true, ElementGroup.IB, 4, 1085, 2567, 8.96),
    Zn("Zn", 65.39, 30, Valence.of(2), true, ElementGroup.IIB, 4, 419.53, 907, 7.14),
    Ga("Ga", 69.72, 31, Valence.of(3), true, ElementGroup.IIIA, 4, 29.76, 2477, 5.91),
    Ge("Ge", 72.64, 32, Valence.of(4, 2), false, ElementGroup.IVA, 4, 937, 2830, 5.32),
    As("As", 74.92, 33, Valence.of(3, 5, -3), false, ElementGroup.VA, 4, 817, 613, 5.73),
    Se("Se", 78.96, 34, Valence.of(6, 4, 2), false, ElementGroup.VIA, 4, 220, 685, 4.82),
    Br("Br", 79.90, 35, Valence.of(7, 5, 1), false, ElementGroup.VIIA, 4, -7.2, 58.8, 3.12),
    Kr("Kr", 83.80, 36, Valence.of(0), false, ElementGroup.VIIIA, 4, -157.36, -153.22, 3.75),
    Rb("Rb", 85.47, 37, Valence.of(1), true, ElementGroup.IA, 5, 39.3, 688, 1.53),
    Sr("Sr", 87.62, 38, Valence.of(2), true, ElementGroup.IIA, 5, 769, 1382, 2.54),
    Y("Y", 88.91, 39, Valence.of(3), true, ElementGroup.IIIB, 5, 1522, 3345, 4.47),
    Zr("Zr", 91.22, 40, Valence.of(4), true, ElementGroup.IVB, 5, 1852, 4377, 6.51),
    Nb("Nb", 92.91, 41, Valence.of(5), true, ElementGroup.VB, 5, 2468, 4741, 8.57),
    Mo("Mo", 95.96, 42, Valence.of(6, 4), true, ElementGroup.VIB, 5, 2623, 4612, 10.28),
    Tc("Tc", 98, 43, Valence.of(7, 4), true, ElementGroup.VIIB, 5, 2157, 4265, 11.49),
    Ru("Ru", 101.1, 44, Valence.of(8, 4, 1), true, ElementGroup.VIIIB, 5, 2263, 3900, 12.37),
    Rh("Rh", 102.9, 45, Valence.of(3, 4), true, ElementGroup.VIIIB, 5, 1966, 3727, 12.45),
    Pd("Pd", 106.4, 46, Valence.of(2, 4), true, ElementGroup.VIIIB, 5, 1554, 2930, 12.02),
    Ag("Ag", 107.9, 47, Valence.of(1), true, ElementGroup.IB, 5, 961.93, 2212, 10.49),
    Cd("Cd", 112.4, 48, Valence.of(2), true, ElementGroup.IIB, 5, 321.07, 765, 8.65),
    In("In", 114.8, 49, Valence.of(3), true, ElementGroup.IIIA, 5, 156.61, 2345, 7.31),
    Sn("Sn", 118.7, 50, Valence.of(4, 2), true, ElementGroup.IVA, 5, 231.93, 2270, 7.31),
    Sb("Sb", 121.8, 51, Valence.of(3, 5, -3), false, ElementGroup.VA, 5, 630.63, 1750, 6.69),
    Te("Te", 127.6, 52, Valence.of(6, 4, 2), false, ElementGroup.VIA, 5, 449.51, 990, 6.24),
    I("I", 126.9, 53, Valence.of(7, 5, 1), false, ElementGroup.VIIA, 5, 113.5, 184.35, 4.93),
    Xe("Xe", 131.3, 54, Valence.of(8, 6, 4), false, ElementGroup.VIIIA, 5, -111.76, -108.08, 5.49),
    Cs("Cs", 133, 55, Valence.of(1), true, ElementGroup.IA, 6, 28.44, 671, 1.93),
    Ba("Ba", 137.3, 56, Valence.of(2), true, ElementGroup.IIA, 6, 725, 1640, 3.59),
    La("La", 139, 57, Valence.of(3), true, ElementGroup.IIIB, 6, 920, 3469, 6.15),
    Ce("Ce", 140, 58, Valence.of(3, 4), true, ElementGroup.IIIB, 6, 795, 3257, 6.77),
    Pr("Pr", 141, 59, Valence.of(3), true, ElementGroup.IIIB, 6, 931, 3128, 6.76),
    Nd("Nd", 144, 60, Valence.of(3), true, ElementGroup.IIIB, 6, 1021, 3074, 7.01),
    Pm("Pm", 145, 61, Valence.of(3), true, ElementGroup.IIIB, 6, 1192, 2800, 7.26),
    Sm("Sm", 150.5, 62, Valence.of(3), true, ElementGroup.IIIB, 6, 1074, 1900, 7.52),
    Eu("Eu", 152, 63, Valence.of(3), true, ElementGroup.IIIB, 6, 822, 1600, 5.25),
    Gd("Gd", 157, 64, Valence.of(3), true, ElementGroup.IIIB, 6, 1313, 3243, 7.9),
    Tb("Tb", 159, 65, Valence.of(3), true, ElementGroup.IIIB, 6, 1356, 3296, 8.23),
    Dy("Dy", 162.5, 66, Valence.of(3), true, ElementGroup.IIIB, 6, 1412, 2562, 8.55),
    Ho("Ho", 165, 67, Valence.of(3), true, ElementGroup.IIIB, 6, 1474, 2700, 8.8),
    Er("Er", 167, 68, Valence.of(3), true, ElementGroup.IIIB, 6, 1529, 2868, 9.07),
    Tm("Tm", 169, 69, Valence.of(3), true, ElementGroup.IIIB, 6, 1545, 1730, 9.32),
    Yb("Yb", 173, 70, Valence.of(3, 2), true, ElementGroup.IIIB, 6, 824, 1469, 6.98),
    Lu("Lu", 175, 71, Valence.of(3), true, ElementGroup.IIIB, 6, 1656, 3395, 9.84),
    Hf("Hf", 178.5, 72, Valence.of(4), true, ElementGroup.IVB, 6, 2233, 4603, 13.31),
    Ta("Ta", 181, 73, Valence.of(5), true, ElementGroup.VB, 6, 3017, 5425, 16.69),
    W("W", 184, 74, Valence.of(6, 4), true, ElementGroup.VIB, 6, 3422, 5660, 19.3),
    Re("Re", 186, 75, Valence.of(7), true, ElementGroup.VIIB, 6, 3180, 5596, 21.02),
    Os("Os", 190, 76, Valence.of(8, 6, 4), true, ElementGroup.VIIIB, 6, 3045, 5300, 22.59),
    Ir("Ir", 192, 77, Valence.of(9, 6, 4, 3), true, ElementGroup.VIIIB, 6, 2410, 4403, 22.56),
    Pt("Pt", 195, 78, Valence.of(4, 2), true, ElementGroup.VIIIB, 6, 1764, 3825, 21.45),
    Au("Au", 197, 79, Valence.of(3, 1), true, ElementGroup.IB, 6, 1064, 2856, 19.32),
    Hg("Hg", 200.6, 80, Valence.of(2, 1), true, ElementGroup.IIB, 6, -38.83, 356.73, 13.53),
    Tl("Tl", 204.5, 81, Valence.of(3), true, ElementGroup.IIIA, 6, 303.5, 1457, 11.85),
    Pb("Pb", 207, 82, Valence.of(4, 2), true, ElementGroup.IVA, 6, 327.46, 1740, 11.34),
    Bi("Bi", 209, 83, Valence.of(5, 3), true, ElementGroup.VA, 6, 271.3, 1564, 9.78),
    Po("Po", 209, 84, Valence.of(6, 2), false, ElementGroup.VIA, 6, 254, 962, 9.5),
    At("At", 210, 85, Valence.of(5, 7), false, ElementGroup.VIIA, 6, 302, 337, 7.0),
    Rn("Rn", 222, 86, Valence.of(0), false, ElementGroup.VIIIA, 6, -71, -61.7, 9.73),
    Fr("Fr", 223, 87, Valence.of(1), true, ElementGroup.IA, 7, 27, 677, 1.87),
    Ra("Ra", 226, 88, Valence.of(2), true, ElementGroup.IIA, 7, 700, 1737, 5.5),
    Ac("Ac", 227, 89, Valence.of(3), true, ElementGroup.IIIB, 7, 1050, 3275, 10.07),
    Th("Th", 232, 90, Valence.of(4), true, ElementGroup.IIIB, 7, 1750, 4790, 11.72),
    Pa("Pa", 231, 91, Valence.of(5), true, ElementGroup.IIIB, 7, 1572, 4000, 15.37),
    U("U", 238, 92, Valence.of(6, 3, 4), true, ElementGroup.IIIB, 7, 1132.3, 3818, 19.1),
    Np("Np", 237, 93, Valence.of(7, 5), true, ElementGroup.IIIB, 7, 640, 3902, 20.45),
    Pu("Pu", 244, 94, Valence.of(6, 4, 3), true, ElementGroup.IIIB, 7, 640.0, 3505, 19.82),
    Am("Am", 243, 95, Valence.of(3, 5, 7), true, ElementGroup.IIIB, 7, 994, 1757, 13.67),
    Cm("Cm", 247, 96, Valence.of(3), true, ElementGroup.IIIB, 7, 1340, 3818, 13.51),
    Bk("Bk", 247, 97, Valence.of(3, 4), true, ElementGroup.IIIB, 7, 986, 3243, 14.78),
    Cf("Cf", 251, 98, Valence.of(3, 4), true, ElementGroup.IIIB, 7, 900, 3700, 15.1),
    Es("Es", 252, 99, Valence.of(3), true, ElementGroup.IIIB, 7, 860, 1169, 8.54),
    Fm("Fm", 257, 100, Valence.of(3), true, ElementGroup.IIIB, 7, 1800, 3800, 10.5),
    Md("Md", 258, 101, Valence.of(3), true, ElementGroup.IIIB, 7, 1100, 2700, 10.47),
    No("No", 259, 102, Valence.of(3), true, ElementGroup.IIIB, 7, 1100, 3400, 9.9),
    Lr("Lr", 266, 103, Valence.of(3), true, ElementGroup.IIIB, 7, 1620, 3500, 14.8),
    Rf("Rf", 261, 104, Valence.of(4), true, ElementGroup.IVB, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Db("Db", 262, 105, Valence.of(5), true, ElementGroup.VB, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Sg("Sg", 263, 106, Valence.of(6), true, ElementGroup.VIB, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Bh("Bh", 264, 107, Valence.of(7), true, ElementGroup.VIIB, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Hs("Hs", 265, 108, Valence.of(8), true, ElementGroup.VIIIB, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Mt("Mt", 266, 109, Valence.of(0), true, ElementGroup.VIIIB, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Ds("Ds", 269, 110, Valence.of(0), true, ElementGroup.VIIIB, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Rg("Rg", 272, 111, Valence.of(0), true, ElementGroup.IB, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Cn("Cn", 277, 112, Valence.of(0), true, ElementGroup.IIB, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Nh("Nh", 286, 113, Valence.of(3, 1), true, ElementGroup.IIIA, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Fl("Fl", 289, 114, Valence.of(3, 0), true, ElementGroup.IVA, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Mc("Mc", 289, 115, Valence.of(1, 3), true, ElementGroup.VA, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Lv("Lv", 293, 116, Valence.of(4), true, ElementGroup.VIA, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Ts("Ts", 294, 117, Valence.of(-1), false, ElementGroup.VIIA, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN),
    Og("Og", 294, 118, Valence.of(0), false, ElementGroup.VIIIA, 7, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN, ElementUtil.UNKNOWN);

    public static final ElementType Sodium = Na;
    public static final ElementType Potassium = K;
    public static final ElementType Iron = Fe;
    public static final ElementType Copper = Cu;
    public static final ElementType Silver = Ag;
    public static final ElementType Gold = Au;
    public static final ElementType Mercury = Hg;
    public static final ElementType Lead = Pb;
    public static final ElementType Tin = Sn;
    public static final ElementType Antimony = Sb;
    public static final ElementType Tungsten = W;
    public static final ElementType Wolfram   = W;

    private final String symbol;
    private final double relativeAtomicMass;
    private final int protonNumber;
    private final int neutronNumber;
    private final Valence valence;
    private final boolean isMetal;
    private final ElementGroup elementGroup;
    private final int period;
    private final double meltingPoint;
    private final double boilingPoint;
    private final double density;

    ElementType(String symbol, double relativeAtomicMass, int neutronNumber, Valence valence, boolean isMetal, ElementGroup elementGroup, int period, double meltingPoint, double boilingPoint, double density) {
        this.symbol = symbol;
        this.relativeAtomicMass = relativeAtomicMass;
        this.protonNumber = this.ordinal() + 1;
        this.neutronNumber = neutronNumber;
        this.valence = valence;
        this.isMetal = isMetal;
        this.elementGroup = elementGroup;
        this.period = period;
        this.meltingPoint = meltingPoint;
        this.boilingPoint = boilingPoint;
        this.density = density;
    }

    public ElementType getNext() {
        return ElementType.values()[(this.ordinal() + 1) % ElementType.values().length];
    }

    public ElementType getPrevious() {
        return ElementType.values()[(this.ordinal() - 1 + ElementType.values().length) % ElementType.values().length];
    }

    public boolean isRadioactive() {
        if (this.ordinal() > 91) {
            return true;
        }
        return switch (this) {
            case U, Th, Ra, Po, Rn, Ac, Pa, Fr, At -> true;
            default -> false;
        };
    }

    public boolean isGas() {
        return switch (this) {
            case H, N, O, F, Cl, He, Ne, Ar, Kr, Xe, Rn -> true;
            default -> false;
        };
    }

    public int getRoundedRelativeAtomicMass() {
        return (int) Math.round(this.relativeAtomicMass);
    }

    public int getMassByRelativeAtomicMass(double amount) {
        return (int) (getRoundedRelativeAtomicMass() * amount);
    }

}
